'use strict';

/** 150 dares. */
module.exports = [
  'Send the last photo in your gallery to this chat.',
  'Type your next 3 messages using only emojis.',
  'Change your WhatsApp bio to "I lost a dare" for 1 hour.',
  'Send a voice note singing the chorus of any song.',
  'Text a random contact "I know what you did" and screenshot the reply.',
  'Set your profile picture to a cartoon character for 30 minutes.',
  'Send a voice note laughing for 20 seconds straight.',
  'Post your most recent selfie in this chat, no filter.',
  'Send the 5th message in your last chat, out of context.',
  'Speak only in third person for the next 10 minutes.',
  'Send a voice note reading your last text message dramatically.',
  'Change your display name to "Eclipse Slave" for one hour.',
  'Call the last person you spoke to and sing happy birthday.',
  'Send a screenshot of your phone battery and step count.',
  'Type a paragraph about why you are the best, in full caps.',
  'Send a photo of your feet. Socks allowed.',
  'Do 20 push-ups and send a voice note counting them.',
  'Text your mother "I have something to tell you" and wait 5 minutes.',
  'Send your most used emoji 50 times.',
  'Let the group choose your profile picture for an hour.',
  'Send a voice note imitating a famous person.',
  'Post a photo of your fridge inside.',
  'Say the alphabet backwards in a voice note.',
  'Send the last video you saved.',
  'Write a poem about the person above you in this chat.',
  'Send a voice note whispering for one full minute.',
  'Text your crush "hey" right now and screenshot it.',
  'Share the last song you played.',
  'Send a photo of your desk exactly as it is.',
  'Do your best animal impression in a voice note.',
  'Type only in lowercase for the next 30 minutes.',
  'Send a screenshot of your most recent notification.',
  'Compliment every person in this chat individually.',
  'Send a voice note rapping any song you know.',
  'Set your status to "Ask me anything" for 15 minutes.',
  'Share your screen time report for today.',
  'Send a photo of what you are wearing right now.',
  'Talk in an accent in your next voice note.',
  'Text "I miss you" to the 4th person in your chat list.',
  'Send the last thing you copied to your clipboard.',
  'Do a 30 second plank and send proof.',
  'Send a voice note explaining your day like a sports commentator.',
  'Post your worst childhood photo.',
  'Let someone here send a message from your phone.',
  'Send a voice note saying "I love pineapple pizza" convincingly.',
  'Write your name with your non-dominant hand and send a photo.',
  'Send an audio of you humming a song for others to guess.',
  'Change your wallpaper to whatever the group chooses.',
  'Send a photo of the nearest book cover.',
  'Text your best friend a made-up dramatic apology.',
  'Sing the national anthem in a voice note.',
  'Send a photo of your current view.',
  'Type a message with your eyes closed and do not correct it.',
  'Send your last three search queries.',
  'Do 10 jumping jacks in a video.',
  'Say a tongue twister three times fast in a voice note.',
  'Send a screenshot of your home screen.',
  'Give a 60 second speech on why socks are important.',
  'Post the oldest photo in your gallery.',
  'Text the group your favourite conspiracy theory.',
  'Talk only in questions for the next 10 messages.',
  'Send a photo of your handwriting.',
  'Send an old school photo of yourself.',
  'Do a dramatic reading of a shampoo bottle label.',
  'Say something nice about the person you argue with most.',
  'Send a photo of the inside of your bag.',
  'Voice note yourself beatboxing for 15 seconds.',
  'Text a friend "we need to talk" and screenshot the response.',
  'Send the most recent meme you saved.',
  'Type your next message using only your nose.',
  'Send a voice note pretending to be a news anchor.',
  'Share the last thing you bought online.',
  'Change your status to a random emoji story.',
  'Do your best evil laugh in a voice note.',
  'Send a photo of your shoes.',
  'Text the person above you a random compliment.',
  'Read your last message in a robot voice.',
  'Post a photo of the ceiling above you.',
  'Send a voice note counting to 20 in another language.',
  'Let the group pick your next status message.',
  'Send the last photo you were tagged in.',
  'Describe your morning routine in a voice note dramatically.',
  'Send a picture of your kitchen sink right now.',
  'Type a message without using the letter E.',
  'Sing a jingle from any advert.',
  'Send your favourite childhood cartoon theme in a voice note.',
  'Take a photo of your face right now, no posing.',
  'Send a message to your family group saying "guess what".',
  'Do 15 squats and report back.',
  'Say the days of the week backwards in a voice note.',
  'Send a photo of the last thing you ate.',
  'Text your last contact a single letter and nothing else.',
  'Give a review of your own personality out of 10 with reasons.',
  'Send a voice note pretending to cry.',
  'Post the last screenshot you took.',
  'Speak in rhymes for your next 5 messages.',
  'Send a photo of your left hand.',
  'Voice note yourself reading a random Wikipedia paragraph.',
  'Change your profile picture to a food item for 30 minutes.',
  'Send the third video in your gallery.',
  'Say something in a baby voice for 20 seconds.',
  'Send a photo of your charging cable situation.',
  'Text a friend "I finally did it" and screenshot the reply.',
  'Type the alphabet as fast as you can and send it.',
  'Send a voice note listing 10 things you hate.',
  'Send your best dance move as a video.',
  'Take a photo of the closest window.',
  'Confess a small secret in a voice note.',
  'Send the last emoji you used 20 times in a row.',
  'Do an impression of someone in this chat.',
  'Send a photo of your phone case.',
  'Read the last group message in a whisper voice note.',
  'Say "I am the greatest" in five different tones.',
  'Send a photo of your bedside table.',
  'Text a random contact a knock-knock joke.',
  'Send a voice note singing your name.',
  'Post your favourite quote and explain why.',
  'Do 10 sit-ups and voice note the count.',
  'Send the last GIF you used.',
  'Speak in a fake foreign accent for the next 5 minutes.',
  'Send a photo of any wall in your house.',
  'Write a haiku about the last person who messaged you.',
  'Voice note yourself narrating what you see right now.',
  'Send your favourite childhood snack photo or name it dramatically.',
  'Give a 30 second motivational speech.',
  'Send a photo of your notes app.',
  'Text the group a random fun fact you believe.',
  'Say tongue twister "she sells seashells" five times fast.',
  'Send a picture of the sky right now.',
  'Sing the chorus of the last song you played.',
  'Type a message using only capital letters and no punctuation.',
  'Send an audio pretending to order food at a restaurant.',
  'Take a mirror selfie and send it.',
  'Send the first photo in your camera roll from this year.',
  'Do a 20 second wall sit and report back.',
  'Text your sibling or cousin something random and screenshot it.',
  'Send a voice note describing the person above you in 3 words.',
  'Set your bio to the last message in this chat for 20 minutes.',
  'Send a photo of your favourite mug or cup.',
  'Voice note yourself doing a countdown from 10 dramatically.',
  'Send the last document you opened, name only.',
  'Do your best superhero pose and send it.',
  'Say your full name in the most dramatic way possible.',
  'Send a photo of the nearest plant or tree.',
  'Type your next message backwards.',
  'Send a voice note thanking the group for nothing.',
  'Give a compliment to the person you know least here.',
  'Send a photo of what is directly to your right.',
  'End the round by sending a voice note saying "Eclipse V1 owns me".',
  'Send a voice note saying the last thing you thought about, out loud.',
];
