'use strict';

/** 150 facts. */
module.exports = [
  'Honey never spoils — 3000-year-old honey from Egyptian tombs is still edible.',
  'Octopuses have three hearts and blue blood.',
  'Bananas are berries, but strawberries are not.',
  'A day on Venus is longer than a year on Venus.',
  'The Eiffel Tower can grow about 15 cm taller in summer.',
  'Sharks existed before trees did.',
  'Wombat droppings are cube shaped.',
  'The human nose can distinguish over one trillion different scents.',
  'A group of flamingos is called a flamboyance.',
  'Sea otters hold hands while sleeping so they do not drift apart.',
  'The Sahara desert was once green grassland with lakes.',
  'Cows have best friends and get stressed when separated.',
  'Your stomach lining replaces itself every few days to avoid digesting itself.',
  'Lightning strikes Earth about 8 million times a day.',
  'A bolt of lightning is roughly five times hotter than the surface of the Sun.',
  'The shortest war in history lasted 38 minutes.',
  'Bees can recognise human faces.',
  'There are more stars in the universe than grains of sand on Earth.',
  'Water can boil and freeze at the same time at the triple point.',
  'The Great Wall of China is not visible from space with the naked eye.',
  'Humans share about 60% of their DNA with bananas.',
  'A blue whale\'s heart can weigh as much as a small car.',
  'Sloths can hold their breath longer than dolphins.',
  'Butterflies taste with their feet.',
  'The Moon is slowly drifting away from Earth, about 3.8 cm per year.',
  'Antarctica is the world\'s largest desert.',
  'Pineapples take about two years to grow.',
  'An octopus can squeeze through any hole larger than its beak.',
  'The dot over a lowercase i or j is called a tittle.',
  'Peanuts are not nuts — they are legumes.',
  'A cloud can weigh more than a million pounds.',
  'Hot water can freeze faster than cold water in some conditions.',
  'The inventor of the frisbee was turned into a frisbee after death.',
  'Scotland has 421 words for snow.',
  'Cats have a special collarbone that lets them always land upright.',
  'A snail can sleep for three years.',
  'Elephants are the only animals that cannot jump.',
  'The heart of a shrimp is located in its head.',
  'Slugs have four noses.',
  'It is impossible to hum while holding your nose closed.',
  'The unicorn is the national animal of Scotland.',
  'Rats laugh when tickled, at frequencies humans cannot hear.',
  'A jiffy is an actual unit of time: 1/100th of a second.',
  'The longest word without a vowel is "rhythms".',
  'Venus is the only planet that spins clockwise.',
  'Bananas are naturally slightly radioactive.',
  'Some turtles can breathe through their rear ends.',
  'The average person walks the equivalent of five times around the world in a lifetime.',
  'A single strand of spaghetti is called a spaghetto.',
  'The Hawaiian alphabet has only 13 letters.',
  'Polar bear skin is black under their transparent fur.',
  'Giraffes only need about 30 minutes of sleep a day.',
  'A crocodile cannot stick out its tongue.',
  'Humans are the only animals with chins.',
  'The Pacific Ocean contains more than half of all free water on Earth.',
  'Mount Everest grows about 4 mm taller every year.',
  'Sound travels about four times faster in water than in air.',
  'The average cumulus cloud floats because its droplets are tiny.',
  'Your body contains roughly the same number of bacteria as human cells.',
  'Fingernails grow about four times faster than toenails.',
  'The first computer bug was an actual moth stuck in a relay.',
  'The word "robot" comes from the Czech word for forced labour.',
  'The first webcam watched a coffee pot at Cambridge University.',
  'Nintendo was founded in 1889 as a playing card company.',
  'The QWERTY layout was designed for mechanical typewriters, not speed.',
  'The @ symbol is called a "monkey tail" in Dutch.',
  'The first item sold on eBay was a broken laser pointer.',
  'Email existed before the World Wide Web.',
  'More than 90% of the world\'s currency exists only digitally.',
  'The first YouTube video was uploaded in April 2005 at a zoo.',
  'The Google homepage was minimal because the founders did not know HTML well.',
  'The word "algorithm" comes from mathematician al-Khwarizmi.',
  'The first 1 GB hard drive weighed over 250 kg.',
  'There are more possible chess games than atoms in the observable universe.',
  'A "gigabyte" of data would fill roughly 65,000 pages of text.',
  'The Firefox logo is actually a red panda.',
  'Wi-Fi does not stand for anything — it is just a brand name.',
  'The first text message ever sent said "Merry Christmas".',
  'Bluetooth is named after a Danish king, Harald Bluetooth.',
  'The average smartphone has more computing power than NASA had in 1969.',
  'The Apollo 11 guidance computer had about 4 KB of RAM.',
  'The world\'s first website is still online.',
  'The term "spam" for junk mail comes from a Monty Python sketch.',
  'CAPTCHA stands for a test to tell computers and humans apart.',
  'The first domain name ever registered was symbolics.com.',
  'Over 300 hours of video are uploaded to YouTube every minute.',
  'The word "byte" was coined to avoid confusion with "bit".',
  'Amazon started as an online bookstore in a garage.',
  'The average person unlocks their phone dozens of times per day.',
  'The first mobile phone call was made in 1973.',
  'A "hertz" measures cycles per second, named after Heinrich Hertz.',
  'Programming language Python is named after Monty Python.',
  'The first emoji set was created in Japan in 1999.',
  'The Internet weighs roughly the same as a strawberry in electron mass terms.',
  'Most passwords are cracked because they are reused, not guessed.',
  'The average person blinks about 15 to 20 times per minute.',
  'Your brain uses about 20% of your body\'s energy.',
  'Human bones are roughly five times stronger than steel by weight.',
  'You lose about 30,000 to 40,000 skin cells every hour.',
  'The strongest muscle by weight is the masseter in the jaw.',
  'Your heart beats about 100,000 times a day.',
  'Humans glow faintly in the dark, too faint for our eyes to see.',
  'The small intestine is about 6 metres long.',
  'Babies are born with around 300 bones; adults have 206.',
  'Your left lung is smaller than your right to make room for the heart.',
  'The cornea is the only part of the body with no blood supply.',
  'Taste buds are replaced roughly every 10 days.',
  'The human eye can detect a candle flame from kilometres away in the dark.',
  'Laughing lowers stress hormones and boosts immune cells.',
  'Your sense of smell is strongest in the evening.',
  'It takes about 20 minutes for your brain to register fullness.',
  'The liver can regenerate from as little as 25% of its tissue.',
  'Sneezes can travel faster than 150 km/h.',
  'Hair is the second fastest growing tissue in the body.',
  'You cannot tickle yourself because your brain predicts the sensation.',
  'The Amazon rainforest produces around 20% of the world\'s oxygen.',
  'The Dead Sea is so salty you float effortlessly.',
  'Russia spans 11 time zones.',
  'Canada has more lakes than the rest of the world combined.',
  'Africa is the only continent in all four hemispheres.',
  'Vatican City is the smallest country in the world.',
  'Nigeria has over 500 spoken languages.',
  'The Nile and the Amazon compete for the title of longest river.',
  'Iceland has no mosquitoes.',
  'Japan has more than 6,800 islands.',
  'Lake Baikal holds about 20% of the world\'s unfrozen fresh water.',
  'Australia is wider than the Moon\'s diameter.',
  'The Atacama Desert has places where rain has never been recorded.',
  'Istanbul is the only city on two continents.',
  'Alaska is both the westernmost and easternmost US state.',
  'Bhutan measures Gross National Happiness.',
  'The Netherlands has more bicycles than people.',
  'Norway introduced salmon sushi to Japan in the 1980s.',
  'The Maldives is the lowest-lying country on Earth.',
  'Egypt\'s pyramids were ancient even to the ancient Romans.',
  'Cleopatra lived closer in time to the Moon landing than to the pyramids.',
  'Oxford University is older than the Aztec Empire.',
  'The Titanic\'s distress signal was one of the first uses of SOS.',
  'Napoleon was not unusually short by the standards of his time.',
  'The Olympic flame is lit using sunlight in Olympia, Greece.',
  'Vikings never wore horned helmets.',
  'The guillotine was last used in France in 1977.',
  'Coca-Cola was originally green? No — the liquid was always caramel coloured.',
  'The world\'s oldest known recipe is for beer.',
  'Ancient Romans used crushed mouse brains as toothpaste.',
  'The fax machine was invented before the telephone.',
  'The first Olympic games had only one event: a footrace.',
  'The word "salary" comes from salt payments to Roman soldiers.',
  'A group of crows is called a murder.',
  'The Moon has moonquakes that can last for almost an hour.',
];
