'use strict';

/**
 * 150 local text memes used as a fallback when the meme image API is
 * unreachable, and by `.textmeme`.
 */
module.exports = [
  { top: 'Me: I will sleep early tonight', bottom: 'Also me at 3 a.m.: what if the Titanic had a sunroof' },
  { top: 'Nobody:', bottom: 'My phone at 1% battery: I can do this all day' },
  { top: 'Boss: we are like a family here', bottom: 'Also boss: denies leave request' },
  { top: 'Me opening the fridge for the 8th time', bottom: 'Hoping the food multiplied' },
  { top: 'Teacher: the exam is easy', bottom: 'The exam: define the universe and give two examples' },
  { top: 'When you finally fix the bug', bottom: 'And 12 new ones appear' },
  { top: 'Me: I only need 5 more minutes', bottom: 'The clock: 2 hours later' },
  { top: 'When your code works and you do not know why', bottom: 'Do not touch anything' },
  { top: 'My bank account after payday', bottom: 'Gone. Reduced to atoms.' },
  { top: 'Me: I am on a diet', bottom: 'The jollof rice: you sure about that?' },
  { top: 'When someone says "we need to talk"', bottom: 'My anxiety: showtime' },
  { top: 'Group project reality', bottom: 'One person works, four people watch' },
  { top: 'When the WiFi drops during a video call', bottom: 'Hello? Hello?? Can you hear me??' },
  { top: 'Me pretending to understand', bottom: 'Nodding aggressively' },
  { top: 'When you send a message and see "typing..." then it stops', bottom: 'What were you going to say?!' },
  { top: 'Monday morning energy', bottom: 'Battery saver mode activated' },
  { top: 'Me googling my symptoms', bottom: 'WebMD: you have 3 days left' },
  { top: 'When someone eats your leftovers', bottom: 'Declaring war' },
  { top: 'Me: this is my last episode', bottom: 'Netflix: next episode in 5...' },
  { top: 'When the teacher says "no phones"', bottom: 'Phone in the sleeve: I am invisible' },
  { top: 'Me at the gym for the first time', bottom: 'Muscles I did not know existed: hello' },
  { top: 'When you laugh at a meme in a quiet room', bottom: 'Everyone: care to share?' },
  { top: 'My browser with 47 tabs open', bottom: 'RAM: I want to leave' },
  { top: 'When your friend says "trust me"', bottom: 'That is exactly when I stop trusting' },
  { top: 'Me trying to save money', bottom: 'Online sale: not today' },
  { top: 'When you wake up before the alarm', bottom: 'Free real estate' },
  { top: 'The mirror at home vs the mirror at the mall', bottom: 'Two different people' },
  { top: 'When you finish a series', bottom: 'Now what is my personality?' },
  { top: 'Me apologising for something I did not do', bottom: 'Just to end the argument' },
  { top: 'When the food arrives at the restaurant', bottom: 'Suddenly everyone is a photographer' },
  { top: 'My motivation on Friday vs Monday', bottom: 'Two entirely different species' },
  { top: 'When someone spoils a movie', bottom: 'Adding them to the list' },
  { top: 'Me: I do not need Google Maps', bottom: 'Also me: lost 3 streets from home' },
  { top: 'When the lecturer says "this will be in the exam"', bottom: 'Suddenly everyone is awake' },
  { top: 'My playlist has 500 songs', bottom: 'I skip 499' },
  { top: 'When you hear your own voice recording', bottom: 'Who is this stranger?' },
  { top: 'Me: I will start tomorrow', bottom: 'Tomorrow: repeats message' },
  { top: 'When the group chat goes silent', bottom: 'Someone send a meme, quick' },
  { top: 'Me holding a door for someone far away', bottom: 'Now we are both uncomfortable' },
  { top: 'When you type a long message and they reply "k"', bottom: 'Unforgivable' },
  { top: 'My alarm at 6 a.m.', bottom: 'My eyes: negotiating a deal' },
  { top: 'When you find money in an old jacket', bottom: 'Certified rich moment' },
  { top: 'Me watching cooking videos', bottom: 'While eating instant noodles' },
  { top: 'When your phone falls face down', bottom: 'Silent prayer time' },
  { top: 'Me: I am fine', bottom: 'The 14 tabs of overthinking in my head: no' },
  { top: 'When someone calls instead of texting', bottom: 'What kind of emergency is this?' },
  { top: 'My data plan on video autoplay', bottom: 'Gone in 60 seconds' },
  { top: 'When the barber says "trust me"', bottom: 'Two weeks indoors' },
  { top: 'Me acting rich on payday', bottom: 'Me acting broke the next day' },
  { top: 'When you remember an embarrassing moment from 2014', bottom: 'Screaming internally' },
  { top: 'My to-do list', bottom: 'Item 1: make a to-do list. Done!' },
  { top: 'When someone says "you look tired"', bottom: 'Thanks, that is my face' },
  { top: 'Me trying to be productive', bottom: 'Cleaning the entire house instead' },
  { top: 'When the meeting could have been an email', bottom: 'One hour of my life gone' },
  { top: 'Me: I will only check my phone for a minute', bottom: 'Two hours later on a random Wikipedia page' },
  { top: 'When your favourite team loses', bottom: 'Suddenly I am a coach' },
  { top: 'When the DJ plays your song', bottom: 'Excuse me, coming through' },
  { top: 'Me trying to whisper', bottom: 'Everyone in a 3 km radius: we heard you' },
  { top: 'When you have to introduce yourself', bottom: 'Forgetting my own name' },
  { top: 'My plants after one week', bottom: 'Me: I did everything right!' },
  { top: 'When you get a notification and it is not a person', bottom: 'Betrayal' },
  { top: 'Me: I do not gossip', bottom: 'Also me: anyway, so...' },
  { top: 'When the electricity goes off mid-download', bottom: 'Pure evil' },
  { top: 'My savings goal vs snack cravings', bottom: 'Snacks win by knockout' },
  { top: 'When you say "hi" and they do not hear you', bottom: 'Pretending to check my pocket' },
  { top: 'Me at 20 vs my back at 25', bottom: 'Warranty expired' },
  { top: 'When your friend drives', bottom: 'Suddenly I believe in God' },
  { top: 'Me reading the terms and conditions', bottom: 'Just kidding, scroll and accept' },
  { top: 'When someone takes the last piece', bottom: 'Silent grudge for life' },
  { top: 'My WiFi when I have work to do', bottom: 'Loading... forever' },
  { top: 'When you overtake someone walking', bottom: 'Now we are racing' },
  { top: 'Me watching a horror movie', bottom: 'Do not go there. They went there.' },
  { top: 'When you finally clean your room', bottom: 'Suddenly a productive genius' },
  { top: 'Me: five more minutes of sleep', bottom: 'Three hours later: why is it dark?' },
  { top: 'When someone corrects your grammar', bottom: 'Thanks, professor' },
  { top: 'My phone storage', bottom: '90% screenshots I will never open' },
  { top: 'When the shop assistant follows you', bottom: 'Suddenly I forgot how to shop' },
  { top: 'Me in a group photo', bottom: 'Blinked. Every single time.' },
  { top: 'When your parents call by your full name', bottom: 'Preparing my will' },
  { top: 'Me: I will drink more water', bottom: 'Water bottle: still full since Monday' },
  { top: 'When the code compiles on the first try', bottom: 'Suspicious. Very suspicious.' },
  { top: 'My weekend plans vs reality', bottom: 'Bed. Just bed.' },
  { top: 'When someone says "quick question"', bottom: 'Forty minutes later' },
  { top: 'Me trying to look busy', bottom: 'Excel spreadsheet with nothing in it' },
  { top: 'When you hear the ice cream truck', bottom: 'Inner child activated' },
  { top: 'My handwriting at the start of the exam', bottom: 'My handwriting at the end: ancient runes' },
  { top: 'When you find the perfect parking spot', bottom: 'Life peaked' },
  { top: 'Me giving advice', bottom: 'Me not following any of it' },
  { top: 'When the movie is better than the book', bottom: 'Blasphemy, apparently' },
  { top: 'My motivation after one push-up', bottom: 'That is enough exercise for the year' },
  { top: 'When you open the camera on the front-facing side', bottom: 'Immediate regret' },
  { top: 'Me: I do not need a list at the market', bottom: 'Comes home with everything except what was needed' },
  { top: 'When someone says "you have changed"', bottom: 'Yes, that is called growth, Susan' },
  { top: 'My sleep schedule', bottom: 'Does not exist. Never did.' },
  { top: 'When the lecturer ends class early', bottom: 'Standing ovation in my heart' },
  { top: 'Me trying a new recipe', bottom: 'Smoke alarm: performing a duet' },
  { top: 'When you get a seat on a full bus', bottom: 'Victory of the century' },
  { top: 'My password: 8 characters', bottom: 'Website: must contain a hieroglyph' },
  { top: 'When you forget why you entered the room', bottom: 'Retracing every step of your life' },
  { top: 'Me pretending to be busy when the boss walks by', bottom: 'Typing gibberish confidently' },
  { top: 'When the food looks nothing like the picture', bottom: 'Expectation vs devastating reality' },
  { top: 'Me trying to save battery', bottom: 'Brightness at 1%, still watching videos' },
  { top: 'When your friend says "I am 5 minutes away"', bottom: 'They just left the house' },
  { top: 'My New Year resolutions', bottom: 'Same list, new year' },
  { top: 'When you finish work at exactly closing time', bottom: 'Speed of light activated' },
  { top: 'Me hearing my name in a random conversation', bottom: 'Full FBI mode' },
  { top: 'When your mum finds your hidden snacks', bottom: 'Case closed by the detective' },
  { top: 'Me at a wedding buffet', bottom: 'Strategy, planning, execution' },
  { top: 'When the app asks for a review after one use', bottom: 'We just met' },
  { top: 'My brain during an exam', bottom: 'Playing a song from 2011 on repeat' },
  { top: 'When someone unmutes to breathe', bottom: 'We heard everything' },
  { top: 'Me: it is just a small purchase', bottom: 'Bank alert: are you sure?' },
  { top: 'When your crush likes your post', bottom: 'Analysing for hidden meaning' },
  { top: 'My chair at work', bottom: 'Knows more about my problems than my therapist' },
  { top: 'When someone says "no offence"', bottom: 'Preparing for maximum offence' },
  { top: 'Me at the ATM after checking my balance', bottom: 'Walking away in silence' },
  { top: 'When you clean your screen mid-video', bottom: 'Accidentally liking a 2019 post' },
  { top: 'My headphones in my pocket for 3 seconds', bottom: 'Now a permanent knot' },
  { top: 'When someone else uses your charger', bottom: 'Territorial dispute begins' },
  { top: 'Me acting normal after almost falling', bottom: 'Nothing happened. Move along.' },
  { top: 'When the group chat plans an outing', bottom: 'Nobody shows up. Classic.' },
  { top: 'My browser history', bottom: 'Cannot be released to the public' },
  { top: 'When you get a compliment', bottom: 'Malfunctioning politely' },
  { top: 'Me trying to be mysterious', bottom: 'Oversharing within 4 minutes' },
  { top: 'When the lift takes too long', bottom: 'Pressing the button 47 times' },
  { top: 'My phone: storage full', bottom: 'Me: deletes one photo and continues' },
  { top: 'When the teacher picks names randomly', bottom: 'Becoming one with the chair' },
  { top: 'Me at 11:59 p.m. on a deadline', bottom: 'Peak performance unlocked' },
  { top: 'When you swap seats and the new one is worse', bottom: 'Choices have consequences' },
  { top: 'My fitness app', bottom: 'Sending guilt notifications since 2019' },
  { top: 'When your favourite snack is out of stock', bottom: 'Emotional damage' },
  { top: 'Me singing in the car', bottom: 'Grammy performance, audience of zero' },
  { top: 'When someone reads your message and does not reply', bottom: 'Building a case in my head' },
  { top: 'My cooking: 10 minutes of prep', bottom: '2 hours of cleaning' },
  { top: 'When you press send and instantly see the typo', bottom: 'Delete for everyone. Fast.' },
  { top: 'Me watching a tutorial at 2x speed', bottom: 'Understanding at 0.5x' },
  { top: 'When the queue moves and the other one is faster', bottom: 'Always the wrong lane' },
  { top: 'My charger cable after 6 months', bottom: 'Held together by hope and tape' },
  { top: 'When you get called to the front of the class', bottom: 'Legs forgot how to leg' },
  { top: 'Me eating healthy for one day', bottom: 'Expecting visible abs immediately' },
  { top: 'When your favourite character dies', bottom: 'Emotionally unavailable for a week' },
  { top: 'My weekend: absolutely nothing', bottom: 'Still exhausted' },
  { top: 'When someone says "guess who"', bottom: 'I have no idea and I am panicking' },
  { top: 'Me trying to fold a fitted sheet', bottom: 'Creating abstract art instead' },
  { top: 'When the group calls you "the funny one"', bottom: 'Pressure of a lifetime' },
  { top: 'My brain at bedtime', bottom: 'Let us solve every problem from 2016' },
  { top: 'When you finally reply to a message from last week', bottom: 'Sorry, just seeing this' },
  { top: 'Me leaving the house', bottom: 'Wallet, keys, phone, existential crisis' },
  { top: 'When you set 12 alarms', bottom: 'And wake up before all of them on a holiday' },
  { top: 'Me explaining a plan to my friend', bottom: 'The plan: there is no plan' },
];
