'use strict';

const { jidNormalizedUser } = require('@whiskeysockets/baileys');
const permissions = require('../utils/permissions');

/**
 * Message ids generated by the bot itself, used for loop prevention.
 */
const botMessageIds = new Set();

function rememberBotMessage(id) {
  if (!id) return;
  botMessageIds.add(id);
  if (botMessageIds.size > 1000) {
    const first = botMessageIds.values().next().value;
    botMessageIds.delete(first);
  }
}

function isBotGenerated(id) {
  return botMessageIds.has(id);
}

function unwrap(message) {
  let content = message;
  while (
    content?.ephemeralMessage?.message ||
    content?.viewOnceMessage?.message ||
    content?.viewOnceMessageV2?.message ||
    content?.viewOnceMessageV2Extension?.message ||
    content?.documentWithCaptionMessage?.message ||
    content?.editedMessage?.message
  ) {
    content =
      content.ephemeralMessage?.message ||
      content.viewOnceMessage?.message ||
      content.viewOnceMessageV2?.message ||
      content.viewOnceMessageV2Extension?.message ||
      content.documentWithCaptionMessage?.message ||
      content.editedMessage?.message;
  }
  return content || {};
}

function getText(content) {
  if (!content) return '';
  return (
    content.conversation ||
    content.extendedTextMessage?.text ||
    content.imageMessage?.caption ||
    content.videoMessage?.caption ||
    content.documentMessage?.caption ||
    content.buttonsResponseMessage?.selectedButtonId ||
    content.listResponseMessage?.singleSelectReply?.selectedRowId ||
    content.templateButtonReplyMessage?.selectedId ||
    ''
  );
}

function getContextInfo(content) {
  return (
    content?.extendedTextMessage?.contextInfo ||
    content?.imageMessage?.contextInfo ||
    content?.videoMessage?.contextInfo ||
    content?.stickerMessage?.contextInfo ||
    content?.audioMessage?.contextInfo ||
    content?.documentMessage?.contextInfo ||
    content?.contextInfo ||
    null
  );
}

function getQuoted(content) {
  const contextInfo = getContextInfo(content);
  const quotedMessage = contextInfo?.quotedMessage;
  if (!quotedMessage) return null;
  return {
    content: unwrap(quotedMessage),
    participant: contextInfo.participant ? permissions.normalizeJid(contextInfo.participant) : null,
    stanzaId: contextInfo.stanzaId || null,
    remoteJid: contextInfo.remoteJid || null,
  };
}

function getMentions(content) {
  const contextInfo = getContextInfo(content);
  return (contextInfo?.mentionedJid || []).map(permissions.normalizeJid);
}

function messageType(content) {
  return Object.keys(content || {})[0] || 'unknown';
}

function senderOf(message) {
  const remoteJid = message.key.remoteJid;
  if (remoteJid?.endsWith('@g.us')) {
    return permissions.normalizeJid(message.key.participant || message.participant || remoteJid);
  }
  if (message.key.fromMe) return null; // resolved to bot jid by caller
  return permissions.normalizeJid(remoteJid);
}

function botJidOf(sock) {
  const id = sock?.user?.id;
  return id ? jidNormalizedUser(id) : '';
}

module.exports = {
  rememberBotMessage,
  isBotGenerated,
  unwrap,
  getText,
  getContextInfo,
  getQuoted,
  getMentions,
  messageType,
  senderOf,
  botJidOf,
};
