'use strict';

/** 150 riddles with answers. */
module.exports = [
  { q: 'I speak without a mouth and hear without ears. What am I?', a: 'An echo' },
  { q: 'The more you take, the more you leave behind. What am I?', a: 'Footsteps' },
  { q: 'What has keys but no locks, space but no room?', a: 'A keyboard' },
  { q: 'What gets wetter the more it dries?', a: 'A towel' },
  { q: 'I have cities but no houses, water but no fish. What am I?', a: 'A map' },
  { q: 'What can travel around the world while staying in a corner?', a: 'A stamp' },
  { q: 'What has hands but cannot clap?', a: 'A clock' },
  { q: 'What has a neck but no head?', a: 'A bottle' },
  { q: 'What has one eye but cannot see?', a: 'A needle' },
  { q: 'What goes up but never comes down?', a: 'Your age' },
  { q: 'What has many teeth but cannot bite?', a: 'A comb' },
  { q: 'What can you catch but not throw?', a: 'A cold' },
  { q: 'What has a bottom at the top?', a: 'Your legs' },
  { q: 'What runs but never walks?', a: 'Water' },
  { q: 'What has a head, a tail, but no body?', a: 'A coin' },
  { q: 'What breaks when you say its name?', a: 'Silence' },
  { q: 'What is full of holes but still holds water?', a: 'A sponge' },
  { q: 'What building has the most stories?', a: 'A library' },
  { q: 'What comes down but never goes up?', a: 'Rain' },
  { q: 'What kind of band never plays music?', a: 'A rubber band' },
  { q: 'What has legs but does not walk?', a: 'A table' },
  { q: 'What has a thumb and four fingers but is not alive?', a: 'A glove' },
  { q: 'What is so fragile that saying its name breaks it?', a: 'Silence' },
  { q: 'What can fill a room but takes up no space?', a: 'Light' },
  { q: 'What has an eye in the middle of a storm?', a: 'A hurricane' },
  { q: 'What has words but never speaks?', a: 'A book' },
  { q: 'What gets bigger the more you take away from it?', a: 'A hole' },
  { q: 'What can you break without touching it?', a: 'A promise' },
  { q: 'What has four wheels and flies?', a: 'A garbage truck' },
  { q: 'What tastes better than it smells?', a: 'A tongue' },
  { q: 'What goes through cities and fields but never moves?', a: 'A road' },
  { q: 'What can you hold in your left hand but never in your right?', a: 'Your right elbow' },
  { q: 'What is always in front of you but cannot be seen?', a: 'The future' },
  { q: 'What has a ring but no finger?', a: 'A telephone' },
  { q: 'What flies without wings?', a: 'Time' },
  { q: 'What can be cracked, made, told and played?', a: 'A joke' },
  { q: 'What has a spine but no bones?', a: 'A book' },
  { q: 'What has 88 keys but cannot open a door?', a: 'A piano' },
  { q: 'What kind of room has no doors or windows?', a: 'A mushroom' },
  { q: 'What has a bed but never sleeps?', a: 'A river' },
  { q: 'What has branches but no fruit, trunk or leaves?', a: 'A bank' },
  { q: 'What can run but has no legs?', a: 'A nose' },
  { q: 'What gets sharper the more you use it?', a: 'Your brain' },
  { q: 'What has a face and two hands but no arms or legs?', a: 'A clock' },
  { q: 'The person who makes it does not need it, the person who buys it does not use it. What is it?', a: 'A coffin' },
  { q: 'What is black when clean and white when dirty?', a: 'A chalkboard' },
  { q: 'What goes up and down but never moves?', a: 'A staircase' },
  { q: 'What has one head, one foot and four legs?', a: 'A bed' },
  { q: 'What can travel the world in a suitcase?', a: 'A passport' },
  { q: 'What has keys, a mouse and a screen but is not alive?', a: 'A computer' },
  { q: 'What comes once in a minute, twice in a moment, but never in a thousand years?', a: 'The letter M' },
  { q: 'What starts with an E, ends with an E, but contains one letter?', a: 'An envelope' },
  { q: 'What is at the end of a rainbow?', a: 'The letter W' },
  { q: 'What word becomes shorter when you add two letters to it?', a: 'Short' },
  { q: 'What five-letter word becomes shorter when you add two letters?', a: 'Short' },
  { q: 'What is the beginning of eternity, the end of time and space?', a: 'The letter E' },
  { q: 'Forward I am heavy, backward I am not. What am I?', a: 'The word "ton"' },
  { q: 'What English word has three consecutive double letters?', a: 'Bookkeeper' },
  { q: 'What word is spelled wrong in every dictionary?', a: 'Wrong' },
  { q: 'What begins with T, ends with T, and has T in it?', a: 'A teapot' },
  { q: 'I am an odd number. Take away a letter and I become even. What am I?', a: 'Seven' },
  { q: 'If two is company and three is a crowd, what are four and five?', a: 'Nine' },
  { q: 'How many months have 28 days?', a: 'All of them' },
  { q: 'A farmer has 17 sheep and all but 9 run away. How many are left?', a: 'Nine' },
  { q: 'What is half of two plus two?', a: 'Three' },
  { q: 'If you have me, you want to share me. If you share me, you no longer have me. What am I?', a: 'A secret' },
  { q: 'What is bought by the yard and worn by the foot?', a: 'A carpet' },
  { q: 'What can be swallowed but can also swallow you?', a: 'Pride' },
  { q: 'What is light as a feather yet no one can hold it for long?', a: 'Breath' },
  { q: 'What is easy to get into but hard to get out of?', a: 'Trouble' },
  { q: 'What does everyone have that they can never lose?', a: 'A shadow — only in darkness' },
  { q: 'What belongs to you but is used more by others?', a: 'Your name' },
  { q: 'What has a heart that does not beat?', a: 'An artichoke' },
  { q: 'What is always coming but never arrives?', a: 'Tomorrow' },
  { q: 'What goes in dry and comes out wet, the longer it stays the stronger it gets?', a: 'A tea bag' },
  { q: 'What kind of coat can only be put on when wet?', a: 'A coat of paint' },
  { q: 'What can be measured but has no length, width or height?', a: 'Temperature' },
  { q: 'What has cities without buildings and mountains without rocks?', a: 'A map' },
  { q: 'What can go up a chimney down but not down a chimney up?', a: 'An umbrella' },
  { q: 'What is dark but made by light?', a: 'A shadow' },
  { q: 'What has a lock but no key, and holds memories?', a: 'A diary' },
  { q: 'What is taken before you get it?', a: 'Your photograph' },
  { q: 'What gets served but never eaten?', a: 'A tennis ball' },
  { q: 'What has four legs in the morning, two at noon and three in the evening?', a: 'A human being' },
  { q: 'What is white when dirty and black when clean?', a: 'A blackboard' },
  { q: 'What kind of tree can you carry in your hand?', a: 'A palm' },
  { q: 'What has roots nobody sees and is taller than trees?', a: 'A mountain' },
  { q: 'Alive without breath, cold as death, never thirsty, ever drinking. What is it?', a: 'A fish' },
  { q: 'Voiceless it cries, wingless it flutters, toothless it bites. What is it?', a: 'The wind' },
  { q: 'This thing devours all: birds, beasts, trees and flowers. What is it?', a: 'Time' },
  { q: 'Thirty white horses on a red hill, first they champ then they stand still. What are they?', a: 'Teeth' },
  { q: 'A box without hinges, key or lid, yet golden treasure inside is hid. What is it?', a: 'An egg' },
  { q: 'What weighs nothing but you can see it?', a: 'Light' },
  { q: 'What has a tail and a head but no legs, and is flipped for luck?', a: 'A coin' },
  { q: 'What can hold water even though it is full of holes?', a: 'A sponge' },
  { q: 'What kind of ship has two mates but no captain?', a: 'A relationship' },
  { q: 'What is orange and sounds like a parrot?', a: 'A carrot' },
  { q: 'What has a bark but no bite?', a: 'A tree' },
  { q: 'What has feathers but does not fly?', a: 'A pillow' },
  { q: 'What has a mouth but never eats?', a: 'A river' },
  { q: 'What goes around the world but stays in one spot?', a: 'A stamp' },
  { q: 'What kind of key opens a banana?', a: 'A monkey' },
  { q: 'What gets passed around but nobody keeps it?', a: 'A ball' },
  { q: 'What has 13 hearts but no organs?', a: 'A deck of cards' },
  { q: 'What breaks on the water but never on land?', a: 'A wave' },
  { q: 'What comes in many colours but always fades?', a: 'A rainbow' },
  { q: 'What can you serve but never eat?', a: 'A summons' },
  { q: 'What has a face that never smiles?', a: 'A clock' },
  { q: 'What is made of water but dies in water?', a: 'Ice' },
  { q: 'What can be long or short, grown or bought, painted or bare?', a: 'A fingernail' },
  { q: 'What has poles but never moves?', a: 'The Earth' },
  { q: 'What is yours but everyone else uses it more than you?', a: 'Your name' },
  { q: 'What can be seen once in a year, twice in a week, never in a day?', a: 'The letter E' },
  { q: 'What loses its head every morning and gets it back at night?', a: 'A pillow' },
  { q: 'What runs all around a garden but never moves?', a: 'A fence' },
  { q: 'What has a thousand needles but cannot sew?', a: 'A porcupine' },
  { q: 'What kind of dog never bites?', a: 'A hot dog' },
  { q: 'What sits in a corner yet travels the world?', a: 'A stamp' },
  { q: 'What can you keep after giving it to someone?', a: 'Your word' },
  { q: 'What kind of table can you eat?', a: 'A vegetable' },
  { q: 'What can jump higher than a building?', a: 'Anything — buildings cannot jump' },
  { q: 'What is invisible until you write with it?', a: 'Ink from an empty pen? No — invisible ink' },
  { q: 'What has one voice yet becomes four-footed, two-footed and three-footed?', a: 'Man' },
  { q: 'What is stolen most often and never reported?', a: 'A heart' },
  { q: 'What is heavier: a kilogram of feathers or a kilogram of stones?', a: 'They weigh the same' },
  { q: 'What word contains all 26 letters?', a: 'Alphabet' },
  { q: 'What is always hungry and must be fed, and turns red when it is fed well?', a: 'Fire' },
  { q: 'What has no beginning, end or middle?', a: 'A circle' },
  { q: 'What has a shell but is not an egg or a nut?', a: 'A tortoise' },
  { q: 'What goes into the water black and comes out red?', a: 'A lobster' },
  { q: 'What is soft as silk and lands without a sound?', a: 'Snow' },
  { q: 'What can pierce the strongest wall without making a hole?', a: 'Sound' },
  { q: 'What travels faster: heat or cold?', a: 'Heat — you can catch a cold' },
  { q: 'What is put on a table, cut, but never eaten?', a: 'A deck of cards' },
  { q: 'What kind of nut has no shell?', a: 'A doughnut' },
  { q: 'What is at the centre of gravity?', a: 'The letter V' },
  { q: 'What is a witch on the beach called?', a: 'A sandwich' },
  { q: 'What has a lot of keys but cannot play a note?', a: 'A janitor' },
  { q: 'What always sleeps with its shoes on?', a: 'A horse' },
  { q: 'What has hundreds of ears but cannot hear?', a: 'A cornfield' },
  { q: 'What can you make that no one can see?', a: 'Noise' },
  { q: 'What is the longest word in the dictionary?', a: 'Smiles — a mile between the two S letters' },
  { q: 'What has a foot on each side and one in the middle?', a: 'A yardstick' },
  { q: 'What has an end but no beginning, and a home but no family?', a: 'A thumb' },
  { q: 'What gets colder the hotter the day becomes?', a: 'A fridge working harder? No — ice cream in a freezer' },
  { q: 'What can you never eat for breakfast?', a: 'Lunch and dinner' },
  { q: 'What is round on both ends and high in the middle?', a: 'Ohio' },
  { q: 'What kind of storm is always in a hurry?', a: 'A dust devil? No — a "brainstorm"' },
  { q: 'What is the only place where today comes before yesterday?', a: 'A dictionary' },
  { q: 'What has a crown but is not a king?', a: 'A tooth' },
];
