'use strict';

/** 150 truth questions. */
module.exports = [
  'What is the most embarrassing thing you have ever done in public?',
  'What is a secret you have never told your family?',
  'Who was your first crush and what happened?',
  'What is the biggest lie you have told to get out of trouble?',
  'Which app do you waste the most time on?',
  'What is something you pretend to like but actually hate?',
  'What is the last lie you told someone in this chat?',
  'Have you ever cheated on a test? How?',
  'What is your most irrational fear?',
  'Who in this group would you swap lives with for a week?',
  'What is the pettiest reason you ever ended a friendship?',
  'What is the worst gift you ever received and who gave it?',
  'Have you ever stalked someone on social media for over an hour?',
  'What is the most money you have ever wasted on something useless?',
  'What is the strangest thing you have ever eaten?',
  'What is a compliment you gave that you did not mean?',
  'Who was the last person you screenshotted a chat with?',
  'What is the longest you have gone without a shower?',
  'What is the worst haircut you have ever had?',
  'Have you ever pretended to be sick to skip something? What was it?',
  'What is your guiltiest pleasure song?',
  'What is the most childish thing you still do?',
  'What is the worst thing you have ever said to a parent?',
  'Have you ever taken credit for someone else\'s work?',
  'Who do you text the most and why?',
  'What is the most embarrassing thing in your search history?',
  'What is one rumour about you that is actually true?',
  'What is the biggest secret you are keeping right now?',
  'Have you ever been rejected? Tell the story.',
  'What is the most awkward date you have been on?',
  'What is something you would never tell your future partner?',
  'Who in this chat would you call at 3 a.m. in an emergency?',
  'What is the meanest thing you have ever done to a sibling?',
  'What is a talent you have that nobody knows about?',
  'What is the most trouble you have been in at school or work?',
  'Have you ever ghosted someone? Why?',
  'What is the worst thing you have done for money?',
  'What is your biggest insecurity?',
  'Who is the last person you thought about before sleeping last night?',
  'Have you ever lied about your age? What for?',
  'What is the most embarrassing thing your parents have caught you doing?',
  'What is one thing you would change about your appearance?',
  'What is the strangest dream you remember?',
  'Have you ever broken something and blamed someone else?',
  'What is the worst advice you have ever given?',
  'What is your most unpopular opinion?',
  'Who do you secretly compare yourself to?',
  'What is something you did as a child that still embarrasses you?',
  'Have you ever eaten food that fell on the floor?',
  'What is your worst habit?',
  'What is the longest you have stayed awake and why?',
  'What is the biggest risk you have ever taken?',
  'Have you ever kept a library book or borrowed item on purpose?',
  'What is something you are secretly proud of?',
  'Who was the last person who made you cry?',
  'What is a text you regret sending?',
  'Have you ever pretended to know someone you did not?',
  'What is the worst movie you actually enjoyed?',
  'What would you do with one million dollars in 24 hours?',
  'What is the most spontaneous thing you have ever done?',
  'What is a fashion choice you regret?',
  'Have you ever snooped through someone else\'s phone?',
  'What is the biggest misunderstanding people have about you?',
  'What is your most used emoji and why?',
  'Who is your celebrity crush right now?',
  'What is the weirdest thing you do when you are alone?',
  'Have you ever fallen asleep in class or a meeting?',
  'What is the most embarrassing nickname you have had?',
  'What is a promise you broke?',
  'What is the hardest goodbye you have said?',
  'Who is the most annoying person you know and why?',
  'What is your most treasured possession?',
  'Have you ever cried over a fictional character?',
  'What is the last thing you Googled?',
  'What is something you are terrible at but pretend to be good at?',
  'What is the biggest mistake you made in the past year?',
  'Have you ever regretted saying "I love you"?',
  'What is your dream job that you will probably never do?',
  'Who in this chat gives the best advice?',
  'What is your biggest turn-off in a person?',
  'What is the most childish argument you have ever had?',
  'Have you ever faked liking a gift? Whose?',
  'What was your worst first impression of someone here?',
  'What is a story about you that everyone tells wrong?',
  'What is your biggest regret from school?',
  'Have you ever cheated in a game to win?',
  'What is the most awkward thing you have said to a stranger?',
  'What would your last meal be?',
  'What is something you would do if nobody could judge you?',
  'Who was the last person you unfollowed and why?',
  'What is the strangest compliment you have received?',
  'What is one thing you would erase from your past?',
  'Have you ever lied to a doctor?',
  'What is the messiest place in your home right now?',
  'What is a food combination you love that others find weird?',
  'What is your worst travel experience?',
  'Have you ever gotten lost? Where?',
  'What is the most number of days you have worn the same clothes?',
  'What is the last thing that made you genuinely laugh?',
  'What is your biggest financial mistake?',
  'Who would you least want to be stuck in a lift with?',
  'What is a rule you break regularly?',
  'What is the last picture you took and why?',
  'What is the most embarrassing thing in your room?',
  'Have you ever been fired or nearly fired?',
  'What is a talent you wish you had?',
  'What is the pettiest thing you have argued about?',
  'What is the most useless skill you have mastered?',
  'What is one thing you would never forgive?',
  'Have you ever pretended to be busy to avoid someone?',
  'What is your favourite thing about yourself?',
  'What is the worst thing you have ever cooked?',
  'What is a secret talent of yours nobody has seen?',
  'Who is the person you trust the least?',
  'What is your biggest pet peeve in a conversation?',
  'What is something you have stolen, even as a joke?',
  'What is the strangest place you have fallen asleep?',
  'What is your worst experience with a teacher or boss?',
  'What is the longest relationship you have had and why did it end?',
  'What is a habit you desperately want to quit?',
  'What is your most embarrassing autocorrect fail?',
  'Have you ever sent a message to the wrong person? What was it?',
  'What is the most trouble a friend has gotten you into?',
  'What is your least attractive quality?',
  'What is a chance you wish you had taken?',
  'What is the strangest thing you have believed as a child?',
  'What is the most embarrassing app on your phone?',
  'What would you name your future children?',
  'Have you ever kept feelings for a friend secret?',
  'What is the worst pain you have experienced?',
  'What is your best kept secret about school or work?',
  'What is a lie you tell yourself?',
  'What is the boldest thing you have ever done for love?',
  'What do you do when nobody is watching?',
  'What is the most childish thing that still makes you happy?',
  'Who in this chat do you think knows you best?',
  'What is your most repeated mistake?',
  'What is the weirdest thing you have searched to help a friend?',
  'What is the most awkward compliment you have given?',
  'What did you think you would be doing at this age?',
  'What is one thing you have never admitted out loud?',
  'What is the last thing you cried about?',
  'What is your greatest fear about the future?',
  'What is the last thing you did that you are ashamed of?',
  'Who is the one person you would forgive for anything?',
  'What is the most impulsive purchase you have made?',
  'What is a memory you would relive forever?',
  'What is the worst thing you have ever done and gotten away with?',
  'What is the one question you hope nobody ever asks you?',
  'What is the one thing you would change about your life right now?',
];
